### ISSUE TITLE
无法执行

### ISSUE THREAD

**Issue by jackmoc** [JaneMandy/Log4j2-Exp#1]
Traceback (most recent call last):
  File "exp.py", line 4, in <module>
    subp = subprocess.call(" ".join(command)+" -u")
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by JaneMandy** [comment]
修改一下Exp.py里面的Path，修改为jdk8的Java8绝对路径。例如：C:\\Program Files\\Java\\jdk1.8.0_301\\bin\\java.exe

**Comment by jackmoc** [comment]
我是linux环境哦

**Comment by JaneMandy** [comment]
这样你需要安装JDK8了，直接在官网下载就行了。

**Comment by jackmoc** [comment]
windows环境OK了  linux环境好像不行   版本如下
[root@ec2-test Log4j2-Exp]# java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

**Comment by jackmoc** [comment]
好了   是我搞混服务器了....
